### ISSUE TITLE
Media Icons not showing

### ISSUE THREAD

**Issue by cdn4lf** [estevez-dev/extended-banner-card#6]
Media icons not showing since 2021.11.0 update.  HA-Icon-button breaking change.

**Comment by michaelhenningersrb** [comment]
Also cover icons are not showing up anymore. Here an example:

![image](https://user-images.githubusercontent.com/18479766/141100536-228a98ac-fb15-4395-8ec6-e2f4d1a303a4.png)

**Comment by airampg** [comment]
Hi guys, I have the same issue. Apparently this is due to the change to icons in the [new version](https://www.home-assistant.io/blog/2021/11/03/release-202111). There is discussion of this for the original [banner card](https://github.com/nervetattoo/banner-card) on issue [#133](https://github.com/nervetattoo/banner-card/issues/133) and also the HACS integration [mini media player](https://github.com/kalkih/mini-media-player) on issue [#559](https://github.com/kalkih/mini-media-player/issues/559). I will have a look at the code and try to use the same fix people have used before, but hopefully, @estevez-dev will be able to implement an official fix for this integration.

**Comment by estevez-dev** [comment]
Sorry guys, I'm not using this card anymore and don't have any spare time to support it. Feel free to fork and fix.
